name: Build Linux
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

concurrency:
  group: environment-lin-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build - ${{ matrix.config.os }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: ubuntu-22.04
            name: "Ubuntu GCC-11"
            artifact: "ubuntu_gcc.7z"
            build_type: "RelWithDebInfo"
            cc: "clang-14"
            cxx: "clang++-14"
            archiver: "7z a"
            generators: "Unix Makefiles"
            build_dir: 'build'
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          ref: master

      - name: Setup
        id: setup
        uses: Silverlan/common_actions/setup@main
          
      - name: Download binaries
        uses: Silverlan/common_actions/download_build_binaries@main
        continue-on-error: true
          
      - name: Build
        id: build
        uses: Silverlan/unirender/github_actions/build@master
        with:
          root_dir: "${{ env.GA_ROOT_DIR }}"
          should_checkout: "0"
          dir: '.'
          build_shared: '1'
          
      - name: Create Release Files
        shell: bash
        run: |
          mkdir release
          mkdir release/lib
          rsync libutil_raytracing.so release/lib/
          rsync third_party_libs/OpenSubdiv/build/lib/libosdGPU.so release/lib/
          rsync third_party_libs/OpenSubdiv/build/lib/libosdCPU.so release/lib/
          rsync --links third_party_libs/OpenSubdiv/build/lib/libosdCPU.so.3.4.3 release/lib/
          rsync --links third_party_libs/OpenSubdiv/build/lib/libosdGPU.so.3.4.3 release/lib/
          rsync third_party_libs/oidn/ispc-v1.18.0-linux/lib64/libispcrt.so release/lib/
          rsync third_party_libs/oidn/build/libOpenImageDenoise.so release/lib/
          rsync build/external_libs/sharedutils/libsharedutils.so release/lib/
          rsync build/external_libs/sharedutils/RelWithDebInfo/libsharedutils.so release/lib/
          rsync build/external_libs/vfilesystem/RelWithDebInfo/libvfilesystem.so release/lib/
          rsync build/external_libs/vfilesystem/libvfilesystem.so release/lib/
          rsync build/external_libs/mathutil/RelWithDebInfo/libmathutil.so release/lib/
          rsync build/external_libs/mathutil/libmathutil.so release/lib/

      - name: Release Binaries
        uses: Silverlan/common_actions/release_nightly_binaries@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit: master

      - name: Handle Error
        uses: Silverlan/common_actions/action_handle_error@main
        if: failure()
